### ISSUE TITLE
(lldb) Crash

### ISSUE THREAD

**Issue by Ragazzetto** [kingandyoga/StyleTransfer-iOS#2]
Hi Kim 
With the latest version of Xcode (Version 9.3) there is a strange behavior...
I noticed that the code crashes to the method
```
+ (UIImage *)pixelBufferBGRToImage:(CVPixelBufferRef)pixelBuffer
                                               width:(CGFloat)outWidth
                                              height:(CGFloat)outHeight
                                         orientation:(UIImageOrientation)orientation{}
```
More precisely, the console returns 
`Thread 1: EXC_BAD_ACCESS (code=1, address=0xe91febeb8)
`
to the code line 
`OSType type = CVPixelBufferGetPixelFormatType(pixelBuffer);
`
of the abovementioned method

Enabling NSZombie makes you realise that the console returns 
`*** -[Not A Type _cfTypeID]: message sent to deallocated instance 0x1c4332480`

With the previous version of Xcode everything worked correctly...
Do you have any ideas about how to solve the problem ?

Thank you so much

Vanni

**Comment by inkImage** [comment]
@JinchengKim Hi,Have you solved the problem?

**Comment by Ragazzetto** [comment]
Hi Kim 
I managed to fix it and realized it's a CoreML bug.
To solve it is necessary to produce a Swift class from CoreML models, if you use an Obj-C class the code crashes inexorably even using the same identical code.
So by adapting only a few lines of code I was able to fix the problem using the Swift classes of CoreML in my Obj-C project.
Bye
Vanni

**Comment by yao2030** [comment]
Is there a way to fix this problem without using Swift ?

**Comment by JinchengKim** [comment]
> Is there a way to fix this problem without using Swift ?

I will fit it this month.

**Comment by yao2030** [comment]
Thanks for your reply. Could you tell me how to fix the problem without using Swift ?

**Comment by hackeritchy** [comment]
> Hi Kim
> I managed to fix it and realized it's a CoreML bug.
> To solve it is necessary to produce a Swift class from CoreML models, if you use an Obj-C class the code crashes inexorably even using the same identical code.
> So by adapting only a few lines of code I was able to fix the problem using the Swift classes of CoreML in my Obj-C project.
> Bye
> Vanni

Hi Vanni:
Could you share it here that how you managed to fixed it? Thank you

**Comment by Ragazzetto** [comment]
> Hi Vanni:
> Could you share it here that how you managed to fixed it? Thank you

Hi hackeritchy
It's very easy
Select the build settings of your target and search coreml
<img width="911" alt="Schermata 2019-04-07 alle 08 56 55" src="https://user-images.githubusercontent.com/12683833/55679978-49917c00-5914-11e9-805d-81e37073b87a.png">
Change coreml model class generation language from automatic to swift

<img width="629" alt="Schermata 2019-04-07 alle 08 59 14" src="https://user-images.githubusercontent.com/12683833/55680053-100d4080-5915-11e9-8096-12fc8996998a.png">
<img width="942" alt="Schermata 2019-04-07 alle 08 59 34" src="https://user-images.githubusercontent.com/12683833/55680055-14395e00-5915-11e9-9a0c-600b6ecae588.png">

As you can see Xcode generate a swift class for your model that you can use in your objC project as every other swift class 
Go and write a good code 😉
